# Credit to Nasit Vurgun for arduino cli workshop: https://git.chalmers.se/courses/dit113/2024/group-7/dit113-ci-workshop/-/blob/main/.gitlab-ci.yml?ref_type=heads

#image: zoobab/arduino-cli:latest
image: ubuntu:latest

before_script:
  - chmod +x ./arduinoCI/arduinoEnv.sh
  - ./arduinoCI/arduinoEnv.sh


stages:
  - compile



build_compile:
  stage: compile
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             
    - pwd                                     
    - cd ./src/main/twoTierApplication/fitVenture/Wio
    - arduino-cli lib list
    - arduino-cli board list
  except:
    - tags

       
